name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

    flutter_bloc: ^8.1.3
    equatable: ^2.0.5
    get_it: ^7.6.0
    injectable: ^2.1.2
    dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true
